resolver:    lts-12.26

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  6aeef7f77be1f6c7d824a4b8eaa14e58daf09b75

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  8d9deaef85b0311d3fe58f3b4cf21efe5e5bf151

- git:     https://github.com/Taiji-pipeline/Taiji-types.git
  commit:  e4f5af754038732a57fcfa6bec67886843aa5afa

- git:     https://github.com/kaizhang/haskell-igraph.git
  commit:  bdaeae380271fdeb183b1eceafdd0d20b1e38fa3

- bioinformatics-toolkit-0.5.1
- HsHTSLib-1.3.2.3
- clustering-0.4.0
