resolver: nightly-2019-03-14

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  bd10c445832a3f3bdf82b57ddf1224397b78390b

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  ebd2608d4cc759db7f43a7cbd125b656bd113494

- git:     https://github.com/Taiji-pipeline/Taiji-types.git
  commit:  9466d7f69977778f50bfdd60fd4fbf62a93dea7b

- git:     https://github.com/kaizhang/bioinformatics-toolkit.git
  commit:  d1ce0f73c04c77edd674cad92904789f5fd46409
  subdirs:
    - bioinformatics-toolkit

- HsHTSLib-1.9.2
- clustering-0.4.1

- diagrams-cairo-1.4.1
- cairo-0.13.6.0
- pango-0.13.6.0
- glib-0.13.7.0
- gtk2hs-buildtools-0.13.5.0
