resolver:    lts-11.3

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  257a1dfe5e7a973f87252bb20074f482022db05f

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  e2ad377101e178c2ff59592c3eea3a696859f61f

- git:     https://github.com/Taiji-pipeline/Taiji-types.git
  commit:  e4f5af754038732a57fcfa6bec67886843aa5afa

- git:     https://github.com/kaizhang/haskell-igraph.git
  commit:  bdaeae380271fdeb183b1eceafdd0d20b1e38fa3

- bioinformatics-toolkit-0.5.0
- HsHTSLib-1.3.2.3
- clustering-0.4.0

- SVGFonts-1.6.0.3
- diagrams-cairo-1.4
- diagrams-core-1.4.0.1
- diagrams-lib-1.4.2
- diagrams-solve-0.1.1
- dual-tree-0.2.1.1
- lens-4.15.4
- free-4.12.4
